<a href="https://colab.research.google.com/github/NadaKhaled99/Work_on_colab/blob/main/Basics_of_Tensorflow/Lesson/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **TensorFlow Tensors learned from Neuralearn.ai.ipynb**


* Notes

1. because we on colab we don't need to instal tensorflow , all we need just import it.












In [2]:
import tensorflow as tf




* **Note:**

1.   variable called tensor_zero_d
2.   Put tensorflow's constant method

3.  Then specify the constant
4.   Constant(value, dtype=None, shape=None, name='Const')


5. The Int32 value type represents signed integers with values ranging from negative 2,147,483,648 through positive 2,147,483,647.


6. Int32 is used to represents 32-bit signed integers(positive and negative)













In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


**Note**:The
shape is the no. of elements and still integers

In [7]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)




Note:The type (float 32)



In [6]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)




* **Note:**

1. shape of 0-D --> is empty
2. shape of 1-D --> is (5,) or (3,) <> ([2,3,4])or ([1,2,3,4,5])
3. shape of 2-D --> is (4,3) <>
([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])








In [8]:
tensor_two_d= tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


**Note:**

1. Put two common not only one common **remember** as
([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]],
                             
])



In [12]:
tensor_three_d =tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


**.shape**

In [16]:
print(tensor_zero_d.shape)

()


In [17]:
print(tensor_one_d.shape)

(3,)


In [18]:
print(tensor_two_d.shape)

(4, 3)


In [19]:
print(tensor_three_d.shape)

(4, 2, 3)


**(1).ndim: it gives us a value of three**

**(2)Showing us that our tensor is a 3-D tensor**





In [21]:
print(tensor_zero_d.shape)

()


In [22]:
print(tensor_one_d.shape)

(3,)


In [23]:
print(tensor_two_d.shape)

(4, 3)


**There is difference between .shape & .ndim**

In [24]:
print(tensor_three_d.ndim)

3


**Try the 4-Dimensional Matrix**

In [29]:
tensor_four_d=tf.constant([

 [
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

],

[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],

],

[
    [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,3,0]],

    [[22,1,9],
    [44,-320,32]],

],

])


print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


**Describe**
**Shape=(3, 4, 2, 3)**
**means:**
1. We have 3d tensor

                  
                  
                       ----- 1
                     ----- 2
                    ---- 3
                1 ----4
                                       
                       ----- 1
                     ----- 2
                    ---- 3
                2 ----4
              
                       ----- 1
                     ----- 2
                    ---- 3
                3 ----4
                  

2. We have 4 array for every 2d tensor       
                                             1
                                           2
                                         3
                                       4

3. we have 2 rows  for every 2d tensor
                                       --  [--]
                                       --  [--]

4. we have 3 columns  for every 1d tensor
                                       |  |  |  |
                                       |  |  |  |
                                       |  |  |  |
                                      [1, 1, 1, 1]  





In [ ]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90],dtype=tf.float)
print(tensor_one_d)

-------------------------